### ISSUE TITLE
Run Tests Provided by "django-regex-redirects" Package & Add New Ones Related to "Wagtail Pages"

### ISSUE THREAD

**Issue by FilipWozniak** [cjkpl/django-cjk404#1]
Fortunately, [django-regex-redirects](https://github.com/maykinmedia/django-regex-redirects) repository included tests (`testsettings.py`), which have not been run yet, so may not function properly. The main objective is to launch them and write new ones, regarding redirects to [Wagtail Pages](https://docs.wagtail.io/en/stable/reference/pages/index.html), not only to URL's.

**Comment by cjkpl** [comment]
Tests added.
